services:
  candy-store-app:
    # build:
    #   context:
    #   dockerfile: Dockerfile
    image: rakesh2221/candy-new:01
    container_name: hello_candy
    user: root
    ports:
      - "3000:3000"
    networks:
      - app-network

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins-server1
    user: root
    volumes:
      - ./jenkins_home:/var/jenkins_home   # Volume mount
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Declare the app-network explicitly
